# ===============================
#  Basic
# ===============================

[[plugins]] # 非同期処理
repo = 'Shougo/vimproc.vim'
build = 'make -f make_mac.mak'

[[plugins]]
repo = 'tpope/vim-pathogen'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
#hook_add = '''
#    let g:lightline = { 
#    \   'colorscheme': 'wombat'
#    \}
#'''

[[plugins]] # Grep高速化
repo = 'rking/ag.vim'

[[plugins]] # 統合ユーザーインタフェース
repo = 'Shougo/unite.vim'

[[plugins]] # Global Tags
repo = 'hewes/unite-gtags'

[[plugins]] # 補完/スニペット
repo = 'Shougo/neocomplete.vim'

[[plugins]] # 補完/スニペット
repo = 'Shougo/neosnippet.vim'

[[plugins]] # 補完/スニペット
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # 文法チェック
repo = 'vim-syntastic/syntastic'

[[plugins]] # タグブラウザ
repo = 'majutsushi/tagbar'

# ===============================
#  Lang
# ===============================

#[[plugins]] # Haml
#repo  = 'tpope/vim-haml'
#on_ft = 'haml'
#
[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # Html5
repo  = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]] # Javascript
repo  = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

#[[plugins]] # Markdown
#repo = 'rcmdnk/vim-markdown'
#on_ft = ['markdown','mkd']
#hook_add = '''
#    let g:vim_markdown_frontmatter = 1
#    let g:vim_markdown_math = 1
#'''

[[plugins]] # Golang
repo = 'fatih/vim-go'
on_ft = 'go'

#[[plugins]] # Japanese doc
#repo = 'vim-jp/vimdoc-ja'
#on_ft = 'help'
#hook_add = '''
#    set helplang=ja,en
#'''
#
# ===============================
#  Colors
# ===============================
#
#[[plugins]] # hybrid
#repo = 'w0ng/vim-hybrid'
#
#[[plugins]] # solarized
#repo = 'altercation/vim-colors-solarized'
