# ===============================
#  Basic
# ===============================

[[plugins]] # 非同期処理
repo = 'Shougo/vimproc.vim'
build = 'make -f make_mac.mak'

[[plugins]] # パッケージマネージャ
repo = 'Shougo/dein.vim'

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = { 
    \   'colorscheme': 'default'
    \}
'''

[[plugins]] # Grep高速化
repo = 'rking/ag.vim'

# [[plugins]] # インタフェース
# repo = 'Shougo/denite.nvim'

[[plugins]] # 補完/スニペット
repo = 'Shougo/neosnippet.vim'

[[plugins]] # スニペット・テンプレート
repo = 'Shougo/neosnippet-snippets'

# [[plugins]] # スニペット・テンプレート
# repo = 'SirVer/ultisnips'

[[plugins]] # 文法チェック
repo = 'neomake/neomake'
hook_add = '''
  autocmd! BufWritePost * Neomake
'''

[[plugins]] # タグブラウザ
repo = 'majutsushi/tagbar'

[[plugins]] # Golang デバッガ 
#repo = 'jodosha/vim-godebug'
repo = 'sebdah/vim-delve'

[[plugins]] # Golang デバッガ (alt)
repo = 'neovim/python-client'

# [[plugins]] # Golang デバッガ 
# repo = 'gilligan/vim-lldb'

[[plugins]] # Golang デバッガ (alt)
repo = 'critiqjo/lldb.nvim'

# ===============================
#  Lang
# ===============================

#[[plugins]] # Haml
#repo  = 'tpope/vim-haml'
#on_ft = 'haml'
#
[[plugins]] # HTML5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # CSS3
repo  = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]] # Javascript
repo  = 'jelera/vim-javascript-syntax'
on_ft = 'javascript'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

#[[plugins]] # Markdown
#repo = 'rcmdnk/vim-markdown'
#on_ft = ['markdown','mkd']
#hook_add = '''
#    let g:vim_markdown_frontmatter = 1
#    let g:vim_markdown_math = 1
#'''

[[plugins]] # Golang
repo = 'fatih/vim-go'
on_ft = 'go'

#[[plugins]] # Japanese doc
#repo = 'vim-jp/vimdoc-ja'
#on_ft = 'help'
#hook_add = '''
#    set helplang=ja,en
#'''
#
# ===============================
#  Colors
# ===============================
#
#[[plugins]] # hybrid
#repo = 'w0ng/vim-hybrid'
#
#[[plugins]] # solarized
#repo = 'altercation/vim-colors-solarized'


# ===============================
#  For NeoVim Bug
# ===============================
[[plugins]] # rectangle paste
repo = 'bfredl/nvim-miniyank'
hook_add = '''
map p <Plug>(miniyank-autoput)
map P <Plug>(miniyank-autoPut)
'''
